import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { getToken } from "next-auth/jwt";
import crypto from "crypto";

/**
 * HOD OTP Generation API
 * 
 * GET /api/hod/otp - List recent OTPs generated by this HOD
 * POST /api/hod/otp - Generate new OTP for a student
 * 
 * OTP Spec:
 * - 6-digit alphanumeric code
 * - 60-second expiry
 * - Stored hashed using SHA256
 * - Max 5 verification attempts
 */

// Helper: Generate 6-digit alphanumeric OTP
function generateOtp(): string {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let otp = '';
    for (let i = 0; i < 6; i++) {
        otp += chars[crypto.randomInt(0, chars.length)];
    }
    return otp;
}

// Helper: Hash OTP for storage
function hashOtp(otp: string): string {
    return crypto.createHash('sha256').update(otp).digest('hex');
}

// GET - List recent OTPs for HOD's department
export async function GET(request: NextRequest) {
    try {
        const token = await getToken({ req: request });
        if (!token || token.role !== "HOD") {
            return NextResponse.json(
                { success: false, error: "Unauthorized" },
                { status: 401 }
            );
        }

        const hod = await prisma.hOD.findUnique({
            where: { userId: token.id as string },
            select: { id: true, departmentId: true }
        });

        if (!hod) {
            return NextResponse.json(
                { success: false, error: "HOD profile not found" },
                { status: 404 }
            );
        }

        // Get recent OTPs for this department (last 24 hours)
        const oneDayAgo = new Date();
        oneDayAgo.setHours(oneDayAgo.getHours() - 24);

        const recentOtps = await prisma.studentOtp.findMany({
            where: {
                departmentId: hod.departmentId,
                createdAt: { gte: oneDayAgo }
            },
            include: {
                student: {
                    include: {
                        user: { select: { name: true, email: true } }
                    }
                }
            },
            orderBy: { createdAt: "desc" },
            take: 50
        });

        // Get students in department for the generation form
        const students = await prisma.student.findMany({
            where: { departmentId: hod.departmentId, isActive: true, isDeleted: false },
            include: {
                user: { select: { name: true, email: true } }
            },
            orderBy: { rollNumber: "asc" }
        });

        return NextResponse.json({
            success: true,
            data: {
                otps: recentOtps.map(otp => ({
                    id: otp.id,
                    studentName: otp.student.user.name,
                    studentEmail: otp.student.user.email,
                    rollNumber: otp.student.rollNumber,
                    createdAt: otp.createdAt,
                    expiresAt: otp.expiresAt,
                    isUsed: otp.isUsed,
                    isExpired: new Date() > otp.expiresAt,
                    attempts: otp.attempts
                })),
                students: students.map(s => ({
                    id: s.id,
                    name: s.user.name,
                    email: s.user.email,
                    rollNumber: s.rollNumber
                }))
            }
        });
    } catch (error) {
        console.error("Get OTPs error:", error);
        return NextResponse.json(
            { success: false, error: "Failed to fetch OTPs" },
            { status: 500 }
        );
    }
}

// POST - Generate new OTP for a student
export async function POST(request: NextRequest) {
    try {
        const token = await getToken({ req: request });
        if (!token || token.role !== "HOD") {
            return NextResponse.json(
                { success: false, error: "Unauthorized" },
                { status: 401 }
            );
        }

        const body = await request.json();
        const { studentId } = body;

        if (!studentId) {
            return NextResponse.json(
                { success: false, error: "Student is required" },
                { status: 400 }
            );
        }

        const hod = await prisma.hOD.findUnique({
            where: { userId: token.id as string },
            select: { id: true, departmentId: true }
        });

        if (!hod) {
            return NextResponse.json(
                { success: false, error: "HOD profile not found" },
                { status: 404 }
            );
        }

        // Verify student belongs to HOD's department
        const student = await prisma.student.findUnique({
            where: { id: studentId },
            include: { user: { select: { name: true } } }
        });

        if (!student || student.departmentId !== hod.departmentId) {
            return NextResponse.json(
                { success: false, error: "Student must be from your department" },
                { status: 403 }
            );
        }

        // Check for existing valid OTP
        const existingValid = await prisma.studentOtp.findFirst({
            where: {
                studentId,
                isUsed: false,
                expiresAt: { gt: new Date() }
            }
        });

        if (existingValid) {
            return NextResponse.json(
                { success: false, error: "Student already has a valid unexpired OTP" },
                { status: 409 }
            );
        }

        // Generate OTP
        const rawOtp = generateOtp();
        const hashedOtp = hashOtp(rawOtp);
        const expiresAt = new Date();
        expiresAt.setSeconds(expiresAt.getSeconds() + 60); // 60 second expiry

        // Create OTP record
        await prisma.studentOtp.create({
            data: {
                studentId,
                departmentId: hod.departmentId,
                otpHash: hashedOtp,
                expiresAt
            }
        });

        return NextResponse.json({
            success: true,
            data: {
                otp: rawOtp, // ONLY returned once to HOD to give to student
                studentName: student.user.name,
                expiresAt: expiresAt.toISOString()
            },
            message: "OTP generated successfully. Valid for 60 seconds."
        }, { status: 201 });
    } catch (error) {
        console.error("Generate OTP error:", error);
        return NextResponse.json(
            { success: false, error: "Failed to generate OTP" },
            { status: 500 }
        );
    }
}
